server:
  port: 1010


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-matricula-service
          uri: lb://ms-matricula-service
          predicates:
            - Path=/inscripcion/**, /matricula/**
          filters:
            - AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-asistencia-service
          uri: lb://ms-asistencia-service
          predicates:
            - Path=/asistencia/**

        - id: ms-docente-service
          uri: lb://ms-docente-service
          predicates:
            - Path=/docente/**, /curso/**

        - id: ms-estudiante-service
          uri: lb://ms-estudiante-service
          predicates:
            - Path=/estudiate/**, /perfil/**

